### ISSUE TITLE
CentOS 7.5 kernel not supported by kernelchecker ?

### ISSUE THREAD

**Issue by chopinesque** [iseletsk/kernelchecker#4]
I just ran 
`# curl -s https://raw.githubusercontent.com/iseletsk/kernelchecker/master/py/kc-compat.py|python`

and got:
UNSUPPORTED

`CentOS Linux 3.10.0-862.3.2.el7.x86_64), no patches available`

**Comment by iseletsk** [comment]
That kernel support was added yesterday. It should work now:
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# curl -s https://raw.githubusercontent.com/iseletsk/kernelchecker/master/py/kc-compat.py|python
COMPATIBLE
